---
application:
  name: "restauracja-jelonek"
  project: "Jelonek"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "restauracja"
  version: "8.0"
routers:
- name: "main-restauracja-jelonek"
  routes:
  - application_name: "restauracja-jelonek"
    paths:
    - "/*"
